# Generated by Django 5.1.3 on 2024-11-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_management', '0001_initial'),
        ('warehouse_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.category', verbose_name='Родительская категория'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='unique_product_constraint'),
        ),
    ]
