version: '3.6'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    networks:
      - internal
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - ../application:/app/
      - ../docker/:/app/docker/

  database:
    restart: always
    image: postgres:15.2
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: Owner
      POSTGRES_PASSWORD: VeryHardPass
      POSTGRES_DB: warehouse_database
      POSTGRES_PORT: 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #ports:
    #  - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 50s
      timeout: 5s
      retries: 5
    networks:
      - internal

  celery:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: celery -A order_in_cel worker -l info --beat
    env_file:
      - .env/
    depends_on:
      - redis
    restart: always
    networks:
      - internal

  redis:
    image: redis:6.2.13-alpine
    networks:
      - internal
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m20s
      timeout: 5s
      retries: 3

networks:
  internal:
volumes:
  postgres_data:
  redis_data:
